ALTER TABLE VlData ADD COLUMN `ID` BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE VlData ADD COLUMN `UUID` VARCHAR(50) NOT NULL DEFAULT 'disa';
ALTER TABLE VlData ADD COLUMN `CREATED_AT` DATETIME NOT NULL DEFAULT NOW();
ALTER TABLE VlData ADD COLUMN `CREATED_BY` VARCHAR(50) NOT NULL DEFAULT 'disa';
ALTER TABLE VlData ADD COLUMN `ENTITY_STATUS` VARCHAR(15) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE VlData ADD COLUMN `UPDATED_AT` DATETIME DEFAULT NULL;
ALTER TABLE VlData ADD COLUMN `UPDATED_BY` VARCHAR(50) DEFAULT NULL;