INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080106","Inhambane","Inhambane","Inhambane Cidade CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010100","Niassa","Lichinga","Lichinga HP");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010106","Niassa","Lichinga","CS Lichinga");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010108","Niassa","Lichinga","Chiuaula PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010111","Niassa","Lichinga","Lulimire CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010115","Niassa","Lichinga","Namacula CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010201","Niassa","Cuamba","Cuamba HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010202","Niassa","Cuamba","Adine 3 CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010209","Niassa","Cuamba","Mitucué CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010216","Niassa","Cuamba","Cuamba CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010225","Niassa","Cuamba","Meripo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010308","Niassa","Lago","Metangula CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010606","Niassa","Mandimba","Mandimba CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1010612","Niassa","Mandimba","Mitande CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1011007","Niassa","Mecanhelas","Chissaua CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1011009","Niassa","Mecanhelas","Entre-Lagos CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1011011","Niassa","Mecanhelas","Mecanhelas CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1011209","Niassa","Metarica","Metarica CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1011409","Niassa","Ngauma","Massangulo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020100","Cabo Delgado","Pemba","Hospital Provincial de Pemba HP");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020106","Cabo Delgado","Pemba","B. Cariacó CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020107","Cabo Delgado","Pemba","B. Ingonane CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020108","Cabo Delgado","Pemba","Natite PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020109","Cabo Delgado","Pemba","B. Cimento CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020110","Cabo Delgado","Pemba","B. Eduardo Mondlane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020111","Cabo Delgado","Pemba","Mahate PS (Cabo Delgado, Cidade De Pemba)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020112","Cabo Delgado","Pemba","B. Muxara PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020206","Cabo Delgado","Ancuabe","Ancuabe CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020207","Cabo Delgado","Ancuabe","Mariri PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020208","Cabo Delgado","Ancuabe","Ntutupue CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020209","Cabo Delgado","Ancuabe","Metoro CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020210","Cabo Delgado","Ancuabe","Meza CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020306","Cabo Delgado","Balama","Balama CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020404","Cabo Delgado","Chiure","Samora Machel CS (Cabo Delgado, Chiure)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020406","Cabo Delgado","Chiure","Chiúre CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020407","Cabo Delgado","Chiure","Chiúre-Velho CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020411","Cabo Delgado","Chiure","Ocúa CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020413","Cabo Delgado","Chiure","Namugelia CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020415","Cabo Delgado","Chiure","Nacoto CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020612","Cabo Delgado","Macomia","Macomia CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020614","Cabo Delgado","Macomia","Chai CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020706","Cabo Delgado","Mecufi","Mecufi CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020809","Cabo Delgado","Meluco","Meluco CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020901","Cabo Delgado","Mocimboa Da Praia","Mocímboa Praia HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1020908","Cabo Delgado","Mocimboa Da Praia","Diaca CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021001","Cabo Delgado","Montepuez","Montepuez HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021011","Cabo Delgado","Montepuez","Namanhumbire PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021015","Cabo Delgado","Montepuez","Montepuez CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021016","Cabo Delgado","Montepuez","Niuhula CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021106","Cabo Delgado","Mueda","Mueda CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021108","Cabo Delgado","Mueda","M'Peme CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021113","Cabo Delgado","Mueda","Mbuo CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021206","Cabo Delgado","Muidumbe","Muambula CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021207","Cabo Delgado","Muidumbe","Chitunda PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021208","Cabo Delgado","Muidumbe","Muatide CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021209","Cabo Delgado","Muidumbe","Miteda PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021212","Cabo Delgado","Muidumbe","Miangalewa CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021306","Cabo Delgado","Namuno","Namuno CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021406","Cabo Delgado","Nangade","Nangade CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021407","Cabo Delgado","Nangade","N'Tamba CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021506","Cabo Delgado","Palma","Palma CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021601","Cabo Delgado","Metuge","Metuge CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1021609","Cabo Delgado","Metuge","Mieze CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030106","Nampula","Nampula","25 de Setembro CS II (Nampula, Cidade De Nampula)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030107","Nampula","Nampula","Marrere CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030108","Nampula","Nampula","1 de Maio CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030109","Nampula","Nampula","Napipine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030110","Nampula","Nampula","Namihepe CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030112","Nampula","Nampula","Namutequeliua PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030113","Nampula","Nampula","Namicopo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030115","Nampula","Nampula","Hospital Psiquiatrico Nampula HP");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030117","Nampula","Nampula","Muhala PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030120","Nampula","Nampula","Mutavarex CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030121","Nampula","Nampula","Niarru CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030201","Nampula","Angoche","Angoche HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030208","Nampula","Angoche","Namitoria PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030301","Nampula","Erati","HD Namapa");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030306","Nampula","Erati","Alua CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030311","Nampula","Erati","Odinepa PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030406","Nampula","Ilha De Moçambique","Ilha de Moç. CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030407","Nampula","Ilha De Moçambique","Lumbo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030506","Nampula","Lalaua","Lalaua CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030606","Nampula","Malema","Malema CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030607","Nampula","Malema","Mutuali CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030706","Nampula","Meconta","Namialo CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030707","Nampula","Meconta","Meconta CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030806","Nampula","Mecuburi","Mecuburi CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1030808","Nampula","Mecuburi","Namina (2) PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031106","Nampula","Mogovolas","Nametil CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031108","Nampula","Mogovolas","Iuluti PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031110","Nampula","Mogovolas","Nanhupo Rio PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031206","Nampula","Moma","Moma CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031207","Nampula","Moma","Chalaua CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031215","Nampula","Moma","Pilivili PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031218","Nampula","Moma","Micane CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031306","Nampula","Monapo","Monapo CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031307","Nampula","Monapo","Carapira CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031308","Nampula","Monapo","Natete CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031318","Nampula","Monapo","CS Monapo Rio");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031406","Nampula","Mossuril","Mossuril CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031411","Nampula","Mossuril","Matibane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031506","Nampula","Muecate","Muecate CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031606","Nampula","Murrupula","Murrupula CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031700","Nampula","Nacala","Nacala-Porto CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031701","Nampula","Nacala","Hospital Distrital de Nacala Porto Hd");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031707","Nampula","Nacala","Quissimajulo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031708","Nampula","Nacala","Murrupelane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031710","Nampula","Nacala","A.D.P.P.Muzuane PSlt");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031715","Nampula","Nacala","Akumi CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031717","Nampula","Nacala","Ontupaia CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031806","Nampula","Nacala-A-Velha","Nacala-A-Velha CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031808","Nampula","Nacala-A-Velha","Barragem PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031811","Nampula","Nacala-A-Velha","Namalala PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1031906","Nampula","Nacaroa","Nacaroa CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032006","Nampula","Rapale","Rapale CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032007","Nampula","Nampula","Anchilo CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032008","Nampula","Rapale","Namaita PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032017","Nampula","Rapale","Namucaua CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032019","Nampula","Nampula","Maratane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032101","Nampula","Ribaue","Ribaue HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032106","Nampula","Ribaue","Yapala-Monapo");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1032110","Nampula","Ribaue","Namiconha CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040100","Zambezia","Quelimane","Hospital Provincial de Quelimane HP");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040106","Zambezia","Quelimane","17 de Setembro CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040107","Zambezia","Quelimane","24 de Julho CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040108","Zambezia","Quelimane","Coalane CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040109","Zambezia","Quelimane","4 de Dezembro CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040110","Zambezia","Quelimane","Cadeia Civil CS (Quelimane)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040111","Zambezia","Quelimane","Namuinho CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040112","Zambezia","Quelimane","Sangarivera PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040114","Zambezia","Quelimane","Chabeco CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040116","Zambezia","Quelimane","Centro de Saude de Micajune");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040117","Zambezia","Quelimane","Centro de Saude de Icidua");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040118","Zambezia","Quelimane","Zalala CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040119","Zambezia","Quelimane","Malanha CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040120","Zambezia","Quelimane","Ionge CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040121","Zambezia","Quelimane","Madal CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040122","Zambezia","Quelimane","Maquival Sede CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040123","Zambezia","Quelimane","Maquival Rio CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040124","Zambezia","Quelimane","Varela CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040125","Zambezia","Quelimane","Inhangulue CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040200","Zambezia","Alto Molocue","Hospital Rural de Alto Molocue HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040213","Zambezia","Alto Molocue","Nauela CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040299","Zambezia","Alto Molocue","Bonifacio Gruveta CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040406","Zambezia","Gile","Alto Ligonha PS -");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040407","Zambezia","Gile","Gilé CS II -");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040408","Zambezia","Gile","Moneia PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040409","Zambezia","Gile","Muiane CS III -");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040410","Zambezia","Gile","Uapé PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040439","Zambezia","Gile","Caiane CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040455","Zambezia","Gile","Mamala CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040506","Zambezia","Gurue","Centro de Saude de Gurue");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040507","Zambezia","Gurue","Lioma CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040601","Zambezia","Ile","Ile CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040608","Zambezia","Ile","Mugulama CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040613","Zambezia","Ile","Socone CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040661","Zambezia","Ile","Namanda CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040706","Zambezia","Inhassunge","Cherimane CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040707","Zambezia","Inhassunge","Gonhane CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040708","Zambezia","Inhassunge","Inhassunge CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040710","Zambezia","Inhassunge","Olinda CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040711","Zambezia","Inhassunge","Bingagira PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040713","Zambezia","Inhassunge","Centro de Saude de Palane-Mucula");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040806","Zambezia","Lugela","Lugela CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040807","Zambezia","Lugela","Munhamade CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040808","Zambezia","Lugela","Namagoa CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040814","Zambezia","Lugela","Putine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040836","Zambezia","Lugela","Mulide CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040902","Zambezia","Maganja Da Costa","Cabuir CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040906","Zambezia","Maganja Da Costa","Maganja da Costa CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040908","Zambezia","Maganja Da Costa","Mabala CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040909","Zambezia","Maganja Da Costa","Moloua CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040911","Zambezia","Maganja Da Costa","Nante CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040913","Zambezia","Maganja Da Costa","Cariua CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040915","Zambezia","Maganja Da Costa","Vila Valdez PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040916","Zambezia","Maganja Da Costa","Alto Mutola PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040917","Zambezia","Maganja Da Costa","Namurrumo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040936","Zambezia","Maganja Da Costa","Mapira CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040937","Zambezia","Maganja Da Costa","Moneia CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1040961","Zambezia","Maganja Da Costa","Muzo CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041000","Zambezia","Milange","Milange HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041004","Zambezia","Milange","Muanhambo CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041006","Zambezia","Milange","Milange CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041007","Zambezia","Milange","Carico PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041010","Zambezia","Milange","Majaua PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041011","Zambezia","Milange","Dulanha CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041012","Zambezia","Milange","Tengua PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041013","Zambezia","Milange","Vulalo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041014","Zambezia","Milange","Liciro PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041015","Zambezia","Milange","Mongue PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041016","Zambezia","Milange","Dachudua PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041017","Zambezia","Milange","CS Nambuzi");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041018","Zambezia","Milange","Gurgunha CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041020","Zambezia","Milange","Chitambo CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041067","Zambezia","Milange","Sabelua CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041100","Zambezia","Mocuba","Mocuba HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041106","Zambezia","Mocuba","Mocuba CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041107","Zambezia","Mocuba","Mocuba Sisal PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041108","Zambezia","Mocuba","Mugeba CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041109","Zambezia","Mocuba","Muaquiua PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041110","Zambezia","Mocuba","Caiave PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041111","Zambezia","Mocuba","Padre Usera (Privado) CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041112","Zambezia","Mocuba","Muloe CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041113","Zambezia","Mocuba","Intome PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041114","Zambezia","Mocuba","Alto Benfica PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041116","Zambezia","Mocuba","Namanjavira CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041117","Zambezia","Mocuba","Munhiba PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041118","Zambezia","Mocuba","Centro de Saude de Nhaluanda");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041119","Zambezia","Mocuba","Magogodo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041120","Zambezia","Mocuba","Samora Machel CS (Zambezia, Mocuba)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041121","Zambezia","Mocuba","Pedreira CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041122","Zambezia","Mocuba","Mataia CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041136","Zambezia","Mocuba","Muanaco CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041137","Zambezia","Mocuba","16 de Junho CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041155","Zambezia","Mocuba","Chimbua CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041156","Zambezia","Mocuba","Namabida CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041158","Zambezia","Mocuba","Namagoa CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041206","Zambezia","Mopeia","Chimuara PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041208","Zambezia","Mopeia","Lua-Lua PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041209","Zambezia","Mopeia","Mopeia CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041308","Zambezia","Morrumbala","Cumbapo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041311","Zambezia","Morrumbala","Megaza CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041312","Zambezia","Morrumbala","Mepinha CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041313","Zambezia","Morrumbala","Pinda CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041336","Zambezia","Morrumbala","Morrumbala CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041406","Zambezia","Namacurra","Namacurra CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041407","Zambezia","Namacurra","Furquia PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041408","Zambezia","Namacurra","Macuse CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041409","Zambezia","Namacurra","Malei PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041410","Zambezia","Namacurra","Mixixine CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041414","Zambezia","Namacurra","M'Baua CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041415","Zambezia","Namacurra","Muebele PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041416","Zambezia","Namacurra","Mutange CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041417","Zambezia","Namacurra","Muceliua CS UC");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041418","Zambezia","Namacurra","Centro de Saude de Mugubia");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041606","Zambezia","Nicoadala","Ilalane CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041609","Zambezia","Nicoadala","Licuare CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041612","Zambezia","Nicoadala","Marrongane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041613","Zambezia","Nicoadala","Namacata CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041614","Zambezia","Nicoadala","Nicoadala CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041617","Zambezia","Nicoadala","Posto de Saude de Quinta Girassol");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041618","Zambezia","Nicoadala","Amoro Health Center");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041620","Zambezia","Nicoadala","Domela CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041706","Zambezia","Pebane","Pebane CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041708","Zambezia","Pebane","Magiga PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041709","Zambezia","Pebane","Malema CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041711","Zambezia","Pebane","Mulela CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041712","Zambezia","Pebane","Muligode CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041713","Zambezia","Pebane","Naburi CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041715","Zambezia","Pebane","7 de Abril CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041716","Zambezia","Pebane","Impaca CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041717","Zambezia","Pebane","Tomeia PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041737","Zambezia","Pebane","Alto Maganha CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041757","Zambezia","Pebane","Centro de Saude de Pele-Pele");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1041803","Zambezia","Derre","Derre CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042003","Zambezia","Mocubela","Gurai PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042004","Zambezia","Mocubela","Ilha de Idugo");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042005","Zambezia","Mocubela","Maneia CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042006","Zambezia","Mocubela","Mocubela CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042007","Zambezia","Mocubela","Nahico CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042008","Zambezia","Mocubela","Bajone CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042009","Zambezia","Mocubela","Missal CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042010","Zambezia","Mocubela","Tapata CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042104","Zambezia","Molumbo","Molumbo CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042105","Zambezia","Molumbo","Corromana PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1042108","Zambezia","Molumbo","Namucumua CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050100","Tete","Tete","Tete HP");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050106","Tete","Tete","Nº 4 - Bairro Muthemba CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050109","Tete","Tete","Nº 1 - Bairro Magaia CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050110","Tete","Tete","Nº 2 - Bairro Matundo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050111","Tete","Tete","Nº 3 - Bairro Manyanga CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050120","Tete","Tete","Mpadue CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050200","Tete","Angonia","Ulongue HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050207","Tete","Angonia","Dómue CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050210","Tete","Angonia","Lifidzi CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050215","Tete","Angonia","Ulongue CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050301","Tete","Cahora Bassa","Songo HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050308","Tete","Cahora Bassa","Chitima CS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050406","Tete","Changara","Changara CS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050409","Tete","Changara","Dzunga CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050411","Tete","Changara","Mazoe Ponte CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050415","Tete","Changara","M'Saua  CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050608","Tete","Chiuta","Manje CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050701","Tete","Macanga","Furancungo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050809","Tete","Magoe","Daque CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050810","Tete","Magoe","Magoe CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1050811","Tete","Magoe","Mucumbura CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051003","Tete","Moatize","Ncondezi CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051006","Tete","Moatize","Zobue CS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051007","Tete","Moatize","Mameme II CS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051008","Tete","Moatize","Moatize CS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051011","Tete","Moatize","Caphirizange PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051013","Tete","Moatize","CFM CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051017","Tete","Moatize","Cateme CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051018","Tete","Moatize","25 de Setembro CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051101","Tete","Mutarara","Mutarara HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051111","Tete","Mutarara","Inhangoma CS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051505","Tete","Marara","Boroma CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1051507","Tete","Marara","Cachembe CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060100","Manica","Chimoio","Chimoio HP");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060106","Manica","Chimoio","Eduardo Mondlane CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060107","Manica","Chimoio","1º Maio CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060108","Manica","Chimoio","Nhamaonha CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060109","Manica","Chimoio","Chissui CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060110","Manica","Chimoio","7 de Abril CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060112","Manica","Chimoio","Vila Nova CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060200","Manica","Barue","Catandica HD");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060206","Manica","Barue","Cruz de Macossa CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060208","Manica","Barue","Honde CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060209","Manica","Barue","Nhazonia CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060210","Manica","Barue","Nhampassa CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060211","Manica","Barue","Nhassacara CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060216","Manica","Barue","Chuala CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060300","Manica","Gondola","Gondola Sede CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060307","Manica","Gondola","Amatongas CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060309","Manica","Gondola","Inchope CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060313","Manica","Gondola","Muda Serração CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060408","Manica","Guro","Guro - Sede CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060409","Manica","Guro","Mandie CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060506","Manica","Machaze","Bassane CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060507","Manica","Machaze","Chipopopo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060508","Manica","Machaze","Chipudji CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060509","Manica","Machaze","Chitobe CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060510","Manica","Machaze","Mazwissanga CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060511","Manica","Machaze","Save CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060596","Manica","Machaze","Mavende CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060706","Manica","Manica","Manica HD");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060712","Manica","Manica","Machipanda CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060714","Manica","Manica","Messica CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060798","Manica","Manica","4º Congresso CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060806","Manica","Mossurize","Espungabera CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060808","Manica","Mossurize","Dacata CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060809","Manica","Mossurize","Mude CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060810","Manica","Mossurize","Mupengo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060812","Manica","Mossurize","Gunhe CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060813","Manica","Mossurize","Chaiva CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060814","Manica","Mossurize","Garagua CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060906","Manica","Sussundenga","Sussundenga CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060908","Manica","Sussundenga","Munhinga CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060911","Manica","Sussundenga","Dombe CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060913","Manica","Sussundenga","Sembezea CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1060995","Manica","Sussundenga","Darue CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061102","Manica","Vanduzi","Vanduzi CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061103","Manica","Vanduzi","Chigodole CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061104","Manica","Vanduzi","Matsinho CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061106","Manica","Vanduzi","Pungue Sul CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061108","Manica","Vanduzi","IAC CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061203","Manica","Macate","Macate CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061204","Manica","Macate","Marera CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1061205","Manica","Macate","Zembe Centro CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070100","Sofala","Beira","Hospital Central da Beira HC");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070104","Sofala","Beira","Manga Loforte");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070105","Sofala","Beira","Marrocanhe");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070106","Sofala","Beira","Munhava CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070107","Sofala","Beira","Manga Nhaconjo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070109","Sofala","Beira","Ponta Gêa PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070110","Sofala","Beira","Cerâmica CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070111","Sofala","Beira","Chamba PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070112","Sofala","Beira","Chota PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070113","Sofala","Beira","Macurungo PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070114","Sofala","Beira","M. Mascarenha CS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070115","Sofala","Beira","Matadouro PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070116","Sofala","Beira","Nhangau CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070200","Sofala","Buzi","Buzi Sede HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070206","Sofala","Buzi","Bandua CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070207","Sofala","Buzi","Ampara PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070210","Sofala","Buzi","Bura CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070217","Sofala","Buzi","Guara-Guara PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070306","Sofala","Caia","Caia HD");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070308","Sofala","Caia","Murraça CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070312","Sofala","Caia","Sena  CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070315","Sofala","Caia","Nhambalo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070500","Sofala","Cheringoma","Inhaminga CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070600","Sofala","Chibabava","Muxungue CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070604","Sofala","Chibabava","Mutindire CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070606","Sofala","Chibabava","Chibabava-Sede CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070609","Sofala","Chibabava","Hoode PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070706","Sofala","Dondo","Dondo Sede CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070707","Sofala","Dondo","Mafambisse CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070711","Sofala","Dondo","Savane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070713","Sofala","Dondo","Mutua PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070714","Sofala","Dondo","Maxarote PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070716","Sofala","Dondo","Canhandula PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070719","Sofala","Dondo","Igreja Baptista CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070777","Sofala","Dondo","Samora Machel PS (Sofala, Dondo)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070806","Sofala","Gorongosa","Gorongoza-Sede CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1070908","Sofala","Machanga","Machang CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071100","Sofala","Marromeu","Marromeu HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071106","Sofala","Marromeu","Nensa CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071301","Sofala","Nhamatanda","Nhamatanda HR ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071307","Sofala","Nhamatanda","Metuchira Lomaco CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071308","Sofala","Nhamatanda","Lamego CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071312","Sofala","Nhamatanda","Nharuchonga PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071313","Sofala","Nhamatanda","Siluvo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071318","Sofala","Nhamatanda","Tica PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1071321","Sofala","Nhamatanda","Chirassicua CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080111","Inhambane","Inhambane","Muelé PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080206","Inhambane","Funhalouro","Funhalouro CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080306","Inhambane","Govuro","Doane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080307","Inhambane","Govuro","Pande PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080308","Inhambane","Govuro","Save PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080309","Inhambane","Govuro","Nova Mambone CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080311","Inhambane","Govuro","Maluvane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080406","Inhambane","Homoine","Homoine CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080507","Inhambane","Inharrime","Chongola CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080509","Inhambane","Inharrime","Inharrime CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080606","Inhambane","Inhassoro","Inhassoro CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080610","Inhambane","Inhassoro","Centro de Saude  de Mangungumete");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080706","Inhambane","Jangamo","Cumbana CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080707","Inhambane","Jangamo","Jangamo CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080806","Inhambane","Mabote","Mabote CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080807","Inhambane","Mabote","Mussengue CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080901","Inhambane","Massinga","Massinga CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080906","Inhambane","Massinga","Nhachengue PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080910","Inhambane","Massinga","Cangela PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080912","Inhambane","Massinga","Muvamba PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080913","Inhambane","Massinga","Rio Das Pedras PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080915","Inhambane","Massinga","Inhaloi PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1080919","Inhambane","Massinga","Chiunze CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081000","Inhambane","Maxixe","Chicuque HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081006","Inhambane","Maxixe","Maxixe (Urbano) CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081011","Inhambane","Maxixe","Bembe PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081013","Inhambane","Maxixe","Centro de Saude de Mabil");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081016","Inhambane","Maxixe","Manhala CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081107","Inhambane","Morrumbene","Cambine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081109","Inhambane","Morrumbene","Mahangue PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081110","Inhambane","Morrumbene","Sitila CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081111","Inhambane","Morrumbene","Morrumbene CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081114","Inhambane","Morrumbene","Mucoduene CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081206","Inhambane","Panda","Inhassune CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081210","Inhambane","Panda","Panda CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081301","Inhambane","Vilankulo","Vilanculos HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081306","Inhambane","Vilankulo","Belane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081307","Inhambane","Vilankulo","Mapinhane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081308","Inhambane","Vilankulo","Pambarra CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081313","Inhambane","Vilankulo","Chibuene PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081404","Inhambane","Zavala","Chitondo CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081405","Inhambane","Zavala","Quissico - Zavala CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081408","Inhambane","Zavala","Cala (Chambula) PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081409","Inhambane","Zavala","Maundene PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081410","Inhambane","Zavala","Zandamela CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081413","Inhambane","Zavala","Mavila PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081415","Inhambane","Zavala","Muane PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1081416","Inhambane","Zavala","Canda PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090106","Gaza","Xai-Xai","Ngoabi CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090107","Gaza","Xai-Xai","Xai-Xai CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090108","Gaza","Xai-Xai","Patrice Lumumba CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090109","Gaza","Xai-Xai","Praia Xai-Xai PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090113","Gaza","Xai-Xai","Unidade 7 CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090206","Gaza","Bilene","Macia CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090207","Gaza","Bilene","Praia de Bilene PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090208","Gaza","Bilene","Mamonho PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090209","Gaza","Limpopo","Chissano PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090210","Gaza","Bilene","Incaia PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090211","Gaza","Limpopo","Licilo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090212","Gaza","Bilene","Mazivila PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090213","Gaza","Bilene","Messano PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090214","Gaza","Bilene","Olombe PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090215","Gaza","Bilene","Tuane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090216","Gaza","Bilene","Mangol PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090302","Gaza","Chibuto","Posto de Saude de Maqueze");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090303","Gaza","Chibuto","Vila Milénio CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090304","Gaza","Chibuto","Célula Missavene CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090305","Gaza","Chibuto","Coca Mussava CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090306","Gaza","Chibuto","Chibuto HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090307","Gaza","Chibuto","Alto Changane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090308","Gaza","Chibuto","Chipadja PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090309","Gaza","Chibuto","Malehice CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090310","Gaza","Chibuto","Muxaxane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090311","Gaza","Chibuto","Maivene PS (Gaza, Chibuto)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090312","Gaza","Chibuto","Chaimite PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090313","Gaza","Chibuto","Centro de Saude de Chimundo");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090314","Gaza","Chibuto","Centro de Saude de Nhavaquene");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090315","Gaza","Chibuto","Mocotuene CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090317","Gaza","Chibuto","Centro de Saude de Changanine");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090318","Gaza","Chibuto","Meboi CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090408","Gaza","Mapai","Mapai CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090601","Gaza","Chokwe","Manjangue CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090603","Gaza","Chokwe","Carmelo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090605","Gaza","Chokwe","25 de Setembro CS II (Gaza, Chokwe)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090604","Gaza","Chokwe","Chokwe CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090606","Gaza","Chokwe","Chókwè HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090607","Gaza","Chokwe","Zuza CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090609","Gaza","Chokwe","Muianga PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090610","Gaza","Chokwe","Mapapa PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090611","Gaza","Chokwe","N'Wachicolane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090613","Gaza","Chokwe","Machua PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090614","Gaza","Chokwe","Cumba PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090615","Gaza","Chokwe","Chalocuane CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090616","Gaza","Chokwe","Hókwè PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090617","Gaza","Chokwe","Conhane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090618","Gaza","Chokwe","Chiaquelane PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090619","Gaza","Chokwe","Chilembene PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090620","Gaza","Chokwe","Lionde PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090621","Gaza","Chokwe","Massavasse PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090622","Gaza","Chokwe","Posto de Saude de Malhazine");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090625","Gaza","Chokwe","Macunene CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090701","Gaza","Guija","Mbalavala CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090706","Gaza","Guija","Guijá CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090707","Gaza","Guija","Nalazy PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090708","Gaza","Guija","Javanhane CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090709","Gaza","Guija","Chimbembe PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090710","Gaza","Guija","Chinhacanine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090711","Gaza","Guija","Chivonguene PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090712","Gaza","Guija","Mpelane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090713","Gaza","Guija","Mubanguene PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090715","Gaza","Guija","Chibabel Novo CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090806","Gaza","Mabalane","Mabalane CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090807","Gaza","Mabalane","Combomune PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090901","Gaza","Mandlakaze","Manjacaze HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090903","Gaza","Mandlakaze","Ndolene CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090904","Gaza","Chonguene","Matsinhane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090906","Gaza","Mandlakaze","Chidenguele PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090907","Gaza","Mandlakaze","Dengoine CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090908","Gaza","Mandlakaze","Betula PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090911","Gaza","Mandlakaze","Chibonzane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090912","Gaza","Mandlakaze","Macuácua CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090913","Gaza","Chonguene","CS Macupulane");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090914","Gaza","Chonguene","CS Mangunze");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090916","Gaza","Mandlakaze","Muzamane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090917","Gaza","Chonguene","CS Cucuine");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090918","Gaza","Mandlakaze","Chicavane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090919","Gaza","Mandlakaze","Mausse PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090920","Gaza","Mandlakaze","Laranjeiras PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090921","Gaza","Mandlakaze","Tavane CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090927","Gaza","Mandlakaze","Centro de Saude de Incadine");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1090928","Gaza","Mandlakaze","Centro de Saude de Macasselane");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091106","Gaza","Massingir","Massingir CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091201","Gaza","Limpopo","Chicumbane HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091206","Gaza","Chonguene","Banhine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091207","Gaza","Xai-Xai","CS Chilaulane");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091208","Gaza","Limpopo","Chipenhe PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091209","Gaza","Chonguene","Chongoene CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091210","Gaza","Chonguene","Inhacutse PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091211","Gaza","Limpopo","Julius Nyerere PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091212","Gaza","Chonguene","Maciene CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091213","Gaza","Chonguene","Siaia PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091214","Gaza","Limpopo","Zonguene PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091215","Gaza","Limpopo","Vladimir Lénine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091216","Gaza","Chonguene","Nhamavila PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091217","Gaza","Chonguene","Bungane PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091221","Gaza","Xai-Xai","CS Zimilene");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1091222","Gaza","Chonguene","PS Ndambine 2000");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100100","Maputo","Matola","Machava HG");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100106","Maputo","Matola","Matola II CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100107","Maputo","Matola","Machava II CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100108","Maputo","Matola","Matola Gare PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100109","Maputo","Matola","Ndlavela PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100110","Maputo","Matola","Matola I CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100111","Maputo","Matola","São Damanso CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100113","Maputo","Matola","Liberdade CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100114","Maputo","Matola","Boquisso PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100117","Maputo","Matola","Komgolote PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100118","Maputo","Matola","Unidade A PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100119","Maputo","Matola","Cadeia Central PS ");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100122","Maputo","Matola","Centro de Saude de Machava-Bedene");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100125","Maputo","Matola","Muhalaze CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100167","Maputo","Matola","Tsalala CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100206","Maputo","Boane","Boane CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100207","Maputo","Boane","Campuane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100208","Maputo","Boane","Mahubo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100210","Maputo","Boane","Beleluane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100212","Maputo","Boane","Matola-Rio PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100214","Maputo","Boane","Gaiato PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100218","Maputo","Boane","Centro de Saude de Mulotana");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100306","Maputo","Magude","Magude CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100308","Maputo","Magude","Motaze PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100419","Maputo","Manhiça","Xinavane HR");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100402","Maputo","Manhiça","Manhiça CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100406","Maputo","Manhiça","Maragra CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100408","Maputo","Manhiça","Malavela PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100409","Maputo","Manhiça","Maluana CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100410","Maputo","Manhiça","Calanga PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100411","Maputo","Manhiça","Munguine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100412","Maputo","Manhiça","Taninga PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100413","Maputo","Manhiça","Whamatibjana (Palmeira) CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100414","Maputo","Manhiça","Ilha Josina PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100415","Maputo","Manhiça","3 de Fevereiro PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100417","Maputo","Manhiça","Centro de Saude de Chibucutso");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100506","Maputo","Marracuene","Marracuene CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100508","Maputo","Marracuene","Machubo PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100509","Maputo","Marracuene","Michafutene CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100510","Maputo","Marracuene","Nhongonhane (Ed.Mondl.) PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100511","Maputo","Marracuene","Ricatla PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100513","Maputo","Marracuene","Mumemo PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100514","Maputo","Marracuene","Mali CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100555","Maputo","Marracuene","Habel Jafar CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100607","Maputo","Matutuine","Matutúine CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100611","Maputo","Matutuine","Ponta de Ouro PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100612","Maputo","Matutuine","Salamanga PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100706","Maputo","Moamba","Moamba CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100707","Maputo","Moamba","Ressano Garcia CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100708","Maputo","Moamba","Centro de Saude de Corrumane");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100709","Maputo","Moamba","Sabié PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100710","Maputo","Moamba","Tenga PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100712","Maputo","Moamba","Mahulane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100806","Maputo","Namaacha","Namaacha CS I");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100808","Maputo","Namaacha","Goba PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100810","Maputo","Namaacha","Mahelane PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1100811","Maputo","Namaacha","Mafuiane PS (Maputo, Namaacha)");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110101","Cidade De Maputo","Kampfumu","Hospital Central Pediatrico de Maputo HC");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110106","Cidade De Maputo","Kampfumu","Alto-Maé CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110107","Cidade De Maputo","Kampfumu","Maxaquene CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110109","Cidade De Maputo","Kampfumu","Malhangalene CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110110","Cidade De Maputo","Kampfumu","Polana Cimento CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110111","Cidade De Maputo","Kampfumu","Porto CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110202","Cidade De Maputo","Nlhamankulu","José Macamo HG");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110206","Cidade De Maputo","Nlhamankulu","Jose Macamo CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110212","Cidade De Maputo","Nlhamankulu","Xipamanine CSURB");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110214","Cidade De Maputo","Nlhamankulu","Centro de Saude do Chamanculo");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110307","Cidade De Maputo","Kamaxakeni","1º de Maio PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110317","Cidade De Maputo","Kamaxakeni","Polana Caniço CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110401","Cidade De Maputo","Kamavota","Mavalane HG");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110406","Cidade De Maputo","Kamavota","1º de Junho PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110411","Cidade De Maputo","Kamavota","Albasine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110412","Cidade De Maputo","Kamavota","Romão PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110414","Cidade De Maputo","Kamavota","Hulene PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110415","Cidade De Maputo","Kamavota","Pescadores PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110422","Cidade De Maputo","Kamavota","Mavalane CS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110507","Cidade De Maputo","Kamubukwana","Bagamoio CS III");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110508","Cidade De Maputo","Kamubukwana","Hospital Psiquiatrico do Infulene HP");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110511","Cidade De Maputo","Kamubukwana","Magoanine Tenda PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110512","Cidade De Maputo","Kamubukwana","Inhagoia PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110514","Cidade De Maputo","Kamubukwana","Magoanine PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110515","Cidade De Maputo","Kamubukwana","Zimpeto PS");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110609","Cidade De Maputo","Katembe","Catembe CS II");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110613","Cidade De Maputo","Katembe","Incassane PSA");
INSERT INTO OrgUnit(code, province, district, facility) VALUES ("1110708","Cidade De Maputo","Kanyaka","Inhaca PS");
