 INSERT INTO PUBLIC.implementing_partner
            (id,
             enabled,
             mail_list,
             org_name,
             password)
VALUES      (1,
             true,
             NULL,
             'fgh',
             '$2a$10$41nSgDPAlGNFqMwaUnBVl.NgKxz14ipAcj/JluJbipbammDr9BKXu');

INSERT INTO PUBLIC.org_unit
            (code,
             district,
             facility,
             implementing_partner_id,
             province)
VALUES      ('1040111',
             'Quelimane',
             '17 de Setembro CSURB',
             1,
             'Zambézia'),
            ('1040107',
             'Quelimane',
             'Namuinho CS III',
             1,
             'Zambézia'),
            ('1040106',
             'Quelimane',
             '24 de Julho CSURB',
             1,
             'Zambézia'),
            ('1040114',
             'Quelimane',
             'Chabeco CSURB',
             1,
             'Zambézia');

INSERT INTO PUBLIC.vl_data
            (type_of_result,
             id,
             created_at,
             created_by,
             entity_status,
             updated_at,
             updated_by,
             uuid,
             age_in_years,
             authorised_by,
             artregimen,
             breast_feeding,
             data_de_inicio_dotarv,
             dob,
             received_date_time,
             ward,
             final_result,
             firstname,
             hl7sex_code,
             specimen_datetime,
             type_of_sample_collection,
             requesting_facility_code,
             clinical_info,
             authorised_date_time,
             viral_load_status,
             surname,
             location,
             attending_doctor,
             uniqueid,
             not_processing_cause,
             pregnant,
             primeira_linha,
             analysis_date_time,
             reason_for_test,
             referring_requestid,
             registered_date_time,
             limsrejection_desc,
             requestid,
             requesting_district_name,
             requesting_facility_name,
             requesting_province_name,
             limsspecimen_source_code,
             segunda_linha,
             synchronized_by,
             viral_load_result_category,
             attribute1,
             hivvl_viral_load_result,
             last_viral_load_date,
             last_viral_load_result,
             hivvl_viral_loadcapctm,
             hivvl_vrlog_value)
VALUES      ('HIVVL',
             1,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040111',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/5354/97932',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM7094992',
             NULL,
             'Namuinho CS III',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             2,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040114',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/4462/02946',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM8028306',
             NULL,
             'Chabeco CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             3,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040107',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/3369/67655',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM5565646',
             NULL,
             '24 de Julho CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             4,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040106',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/9645/68928',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM3115484',
             NULL,
             '17 de Setembro CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             5,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040111',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/3584/96413',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM4896458',
             NULL,
             'Namuinho CS III',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             6,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040114',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/5682/60341',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM7573923',
             NULL,
             'Chabeco CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133');

INSERT INTO PUBLIC.vl_data
            (type_of_result,
             id,
             created_at,
             created_by,
             entity_status,
             updated_at,
             updated_by,
             uuid,
             age_in_years,
             authorised_by,
             artregimen,
             breast_feeding,
             data_de_inicio_dotarv,
             dob,
             received_date_time,
             ward,
             final_result,
             firstname,
             hl7sex_code,
             specimen_datetime,
             type_of_sample_collection,
             requesting_facility_code,
             clinical_info,
             authorised_date_time,
             viral_load_status,
             surname,
             location,
             attending_doctor,
             uniqueid,
             not_processing_cause,
             pregnant,
             primeira_linha,
             analysis_date_time,
             reason_for_test,
             referring_requestid,
             registered_date_time,
             limsrejection_desc,
             requestid,
             requesting_district_name,
             requesting_facility_name,
             requesting_province_name,
             limsspecimen_source_code,
             segunda_linha,
             synchronized_by,
             viral_load_result_category,
             attribute1,
             hivvl_viral_load_result,
             last_viral_load_date,
             last_viral_load_result,
             hivvl_viral_loadcapctm,
             hivvl_vrlog_value)
VALUES      ('HIVVL',
             7,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040107',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/1513/08319',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM4110303',
             NULL,
             '24 de Julho CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             8,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040106',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/2218/17416',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM6920351',
             NULL,
             '17 de Setembro CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             9,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040111',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/8946/07162',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM5825393',
             NULL,
             'Namuinho CS III',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             10,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040114',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/6315/04052',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM7387902',
             NULL,
             'Chabeco CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             11,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040107',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/8743/22403',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM2114453',
             NULL,
             '24 de Julho CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             12,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             NULL,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040106',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/0126/36403',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM7485860',
             NULL,
             '17 de Setembro CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133');

INSERT INTO PUBLIC.vl_data
            (type_of_result,
             id,
             created_at,
             created_by,
             entity_status,
             updated_at,
             updated_by,
             uuid,
             age_in_years,
             authorised_by,
             artregimen,
             breast_feeding,
             data_de_inicio_dotarv,
             dob,
             received_date_time,
             ward,
             final_result,
             firstname,
             hl7sex_code,
             specimen_datetime,
             type_of_sample_collection,
             requesting_facility_code,
             clinical_info,
             authorised_date_time,
             viral_load_status,
             surname,
             location,
             attending_doctor,
             uniqueid,
             not_processing_cause,
             pregnant,
             primeira_linha,
             analysis_date_time,
             reason_for_test,
             referring_requestid,
             registered_date_time,
             limsrejection_desc,
             requestid,
             requesting_district_name,
             requesting_facility_name,
             requesting_province_name,
             limsspecimen_source_code,
             segunda_linha,
             synchronized_by,
             viral_load_result_category,
             attribute1,
             hivvl_viral_load_result,
             last_viral_load_date,
             last_viral_load_result,
             hivvl_viral_loadcapctm,
             hivvl_vrlog_value)
VALUES      ('HIVVL',
             13,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040111',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/6237/86944',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM5627345',
             NULL,
             'Namuinho CS III',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             14,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040114',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/7380/07402',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM2654943',
             NULL,
             'Chabeco CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             15,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040107',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/8010/42516',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM4981287',
             NULL,
             '24 de Julho CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             16,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040106',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'NOT_PROCESSED',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/5256/08104',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM7058002',
             NULL,
             '17 de Setembro CSURB',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             17,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'INACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1040111',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001041137/9448/07583',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM5288671',
             NULL,
             'Namuinho CS III',
             'Zambezia',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133'),
            ('HIVVL',
             18,
             timestamp '2024-03-20 12:33:34.367',
             'fgh',
             'ACTIVE',
             NULL,
             NULL,
             'b992bd4d-8318-4cdf-ab18-dac1236a624e',
             NULL,
             'ITALIDA',
             NULL,
             'Yes',
             NULL,
             date '2024-03-20',
             timestamp '2024-03-20 12:33:34.366',
             'SMI',
             300,
             NULL,
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Unreported',
             '1100100',
             'N/A',
             timestamp '2024-03-20 12:33:34.367',
             'PENDING',
             NULL,
             NULL,
             'ITALIDA',
             '0001100100/0000/00000',
             NULL,
             'Unreported',
             NULL,
             timestamp '2024-03-20 12:33:34.366',
             'Routine',
             NULL,
             NULL,
             'N/A',
             'MZDISAPQM3693397',
             NULL,
             'Chabeco CSURB',
             'Maputo',
             'DBS',
             NULL,
             NULL,
             'Suppressed',
             NULL,
             NULL,
             NULL,
             NULL,
             '1000',
             '133');  